responses = [
    "I guess this is",
    "To me, this looks like",
    "Hmmm... I think this is",
    "Oh, this is definitely",
    "I guess this is",
    "To me, this looks like",
    "Hmmm... I think this is",
    "Oh, this is definitely",
    "My prediction is",
    "It appears to be",
    "In my opinion, this resembles",
    "I'm leaning towards",
    "My best guess is",
    "Seems like",
    "From what I see, it's",
    "I'd say this is",
    "This looks like",
    "If I had to guess, I'd say",
    "In my estimation, it's",
    "Judging by the features, it could be",
    "I'm getting vibes of",
    "This reminds me of",
    "I'm getting a sense of",
    "My AI instincts tell me it's",
    "It gives off the impression of",
    "There's a possibility it's",
    "Based on my analysis, it's",
    "Looks like the binary code is revealing",
]
